import type { BrandProfile, Campaign, Contract, CreatorProfile } from '../types';

export type CreatorRow = CreatorProfile & { id: string };

const social = (
  links: Array<{ platform: 'instagram' | 'youtube' | 'tiktok' | 'twitter' | 'linkedin'; handle: string; followers: number; engagementRate: number }>
) => links;

const tiers = (
  items: Array<{ type: 'story' | 'feed_post' | 'reel' | 'youtube_video' | 'dedicated_video'; label: string; minPrice: number; maxPrice: number; currency: string }>
) => items;

function creator(base: Omit<CreatorRow, 'socialLinks' | 'pricingTiers'> & { socialLinks?: CreatorRow['socialLinks']; pricingTiers?: CreatorRow['pricingTiers'] }): CreatorRow {
  const {
    socialLinks = social([
      { platform: 'instagram', handle: '@creator', followers: 120000, engagementRate: 4.2 },
      { platform: 'youtube', handle: '@ChannelName', followers: 85000, engagementRate: 3.8 },
    ]),
    pricingTiers = tiers([
      { type: 'story', label: 'Instagram Story', minPrice: 8000, maxPrice: 15000, currency: 'INR' },
      { type: 'reel', label: 'Instagram Reel', minPrice: 25000, maxPrice: 55000, currency: 'INR' },
      { type: 'youtube_video', label: 'YouTube Video', minPrice: 45000, maxPrice: 120000, currency: 'INR' },
    ]),
    ...rest
  } = base;
  return { ...rest, socialLinks, pricingTiers };
}

/** Sample creators for Discover + dashboards when using mock catalog. */
export const MOCK_CREATORS: CreatorRow[] = [
  creator({
    id: 'cr_mock_ananya',
    userId: 'cr_mock_ananya',
    displayName: 'Ananya Rao',
    username: 'ananya.lifestyle',
    bio: 'Bangalore-based lifestyle creator focused on sustainable fashion and honest brand reviews. Previous partners include Myntra, Nykaa, and indie D2C labels.',
    tagline: 'Authentic everyday style · 240K+ combined reach',
    location: 'Bengaluru, India',
    languages: ['English', 'Hindi', 'Kannada'],
    niches: ['Fashion', 'Beauty', 'Lifestyle'],
    availability: 'available',
    portfolioUrls: ['https://instagram.com/ananya.lifestyle'],
    creatorScore: 91,
    creatorTier: 'elite',
    completionPercentage: 98,
    campaignsCompleted: 42,
    onTimeDeliveryRate: 97,
    revisionRate: 8,
    avgResponseTime: '< 4h',
    audienceData: {
      topAgeGroup: '18–34',
      topLocation: 'Metro India',
      genderSplit: { male: 28, female: 69, other: 3 },
    },
    socialLinks: social([
      { platform: 'instagram', handle: '@ananya.lifestyle', followers: 182000, engagementRate: 4.6 },
      { platform: 'youtube', handle: 'Ananya Rao', followers: 94000, engagementRate: 3.9 },
      { platform: 'tiktok', handle: '@ananya.r', followers: 320000, engagementRate: 5.1 },
    ]),
    pricingTiers: tiers([
      { type: 'story', label: 'Story (3 frames)', minPrice: 12000, maxPrice: 22000, currency: 'INR' },
      { type: 'reel', label: 'Reel', minPrice: 35000, maxPrice: 70000, currency: 'INR' },
      { type: 'feed_post', label: 'Carousel', minPrice: 28000, maxPrice: 55000, currency: 'INR' },
    ]),
  }),
  creator({
    id: 'cr_mock_arjun',
    userId: 'cr_mock_arjun',
    displayName: 'Arjun Mehta',
    username: 'techwitharjun',
    bio: 'Tech reviewer and gadget storyteller. Deep dives on audio, wearables, and smart home. ASCI-compliant sponsored segments.',
    tagline: 'Tech that fits real life',
    location: 'Mumbai, India',
    languages: ['English', 'Hindi'],
    niches: ['Tech', 'Gaming'],
    availability: 'busy',
    portfolioUrls: [],
    creatorScore: 88,
    creatorTier: 'verified_pro',
    completionPercentage: 96,
    campaignsCompleted: 67,
    onTimeDeliveryRate: 94,
    revisionRate: 12,
    avgResponseTime: '< 6h',
    socialLinks: social([
      { platform: 'youtube', handle: 'TechWithArjun', followers: 520000, engagementRate: 4.1 },
      { platform: 'instagram', handle: '@techwitharjun', followers: 118000, engagementRate: 3.7 },
      { platform: 'twitter', handle: '@twarjun', followers: 42000, engagementRate: 2.9 },
    ]),
    pricingTiers: tiers([
      { type: 'youtube_video', label: 'Dedicated review (8–12 min)', minPrice: 85000, maxPrice: 180000, currency: 'INR' },
      { type: 'reel', label: 'Short vertical', minPrice: 22000, maxPrice: 45000, currency: 'INR' },
    ]),
  }),
  creator({
    id: 'cr_mock_kavya',
    userId: 'cr_mock_kavya',
    displayName: 'Kavya Nair',
    username: 'fuel.fit.kavya',
    bio: 'Nutrition coach and fitness creator. Recipe reels, workout snippets, and supplement education with science-backed messaging.',
    tagline: 'Stronger habits, zero crash diets',
    location: 'Kochi, India',
    languages: ['English', 'Malayalam'],
    niches: ['Fitness', 'Food', 'Education'],
    availability: 'available',
    portfolioUrls: [],
    creatorScore: 84,
    creatorTier: 'established',
    completionPercentage: 93,
    campaignsCompleted: 29,
    onTimeDeliveryRate: 98,
    revisionRate: 10,
    avgResponseTime: '< 8h',
    socialLinks: social([
      { platform: 'instagram', handle: '@fuel.fit.kavya', followers: 210000, engagementRate: 5.4 },
      { platform: 'youtube', handle: 'Kavya Nair Fitness', followers: 76000, engagementRate: 4.0 },
    ]),
  }),
  creator({
    id: 'cr_mock_rahul',
    userId: 'cr_mock_rahul',
    displayName: 'Rahul Verma',
    username: 'finance.rv',
    bio: 'Personal finance explainer for young professionals — credit cards, mutual funds, and tax-saving instruments without the jargon.',
    tagline: 'Money clarity in under 60 seconds',
    location: 'Gurugram, India',
    languages: ['English', 'Hindi'],
    niches: ['Finance', 'Education'],
    availability: 'not_available',
    portfolioUrls: [],
    creatorScore: 79,
    creatorTier: 'rising',
    completionPercentage: 89,
    campaignsCompleted: 14,
    onTimeDeliveryRate: 100,
    revisionRate: 15,
    avgResponseTime: '< 12h',
    socialLinks: social([
      { platform: 'youtube', handle: 'Finance RV', followers: 410000, engagementRate: 3.5 },
      { platform: 'linkedin', handle: 'rahul-verma-finance', followers: 28000, engagementRate: 4.8 },
    ]),
  }),
  creator({
    id: 'cr_mock_sara',
    userId: 'cr_mock_sara',
    displayName: 'Sara Khan',
    username: 'sara.travel.diaries',
    bio: 'Slow travel and boutique stays across India & SEA. Drone B-roll, cinematic edits, and destination guides for premium hospitality brands.',
    tagline: 'Stories from the road',
    location: 'Goa, India',
    languages: ['English', 'Hindi'],
    niches: ['Travel', 'Music'],
    availability: 'available',
    portfolioUrls: [],
    creatorScore: 86,
    creatorTier: 'established',
    completionPercentage: 95,
    campaignsCompleted: 31,
    onTimeDeliveryRate: 92,
    revisionRate: 11,
    avgResponseTime: '< 5h',
    socialLinks: social([
      { platform: 'instagram', handle: '@sara.travel.diaries', followers: 298000, engagementRate: 4.9 },
      { platform: 'tiktok', handle: '@saratravel', followers: 156000, engagementRate: 5.6 },
    ]),
  }),
  creator({
    id: 'cr_mock_deepa',
    userId: 'cr_mock_deepa',
    displayName: 'Deepa Weds',
    username: 'deepa.weds.co',
    bio: 'Wedding and bridal content creator. Mehendi designs, outfit coordination, and pre-wedding tips for Indian brides.',
    tagline: 'Your wedding just got prettier',
    location: 'Delhi, India',
    languages: ['English', 'Hindi', 'Punjabi'],
    niches: ['Fashion', 'Weddings', 'Lifestyle'],
    availability: 'available',
    portfolioUrls: [],
    creatorScore: 82,
    creatorTier: 'established',
    completionPercentage: 91,
    campaignsCompleted: 26,
    onTimeDeliveryRate: 96,
    revisionRate: 9,
    avgResponseTime: '< 3h',
    socialLinks: social([
      { platform: 'instagram', handle: '@deepa.weds.co', followers: 165000, engagementRate: 5.2 },
      { platform: 'youtube', handle: 'Deepa Weds', followers: 58000, engagementRate: 4.1 },
    ]),
  }),
  creator({
    id: 'cr_mock_vikram',
    userId: 'cr_mock_vikram',
    displayName: 'Vikram Games',
    username: 'vikram.gaming',
    bio: 'Gaming streamer and esports enthusiast. Mobile and console games, game reviews, and competitive gaming highlights.',
    tagline: 'Level up your game',
    location: 'Bangalore, India',
    languages: ['English', 'Hindi'],
    niches: ['Gaming', 'Tech', 'Entertainment'],
    availability: 'available',
    portfolioUrls: [],
    creatorScore: 85,
    creatorTier: 'established',
    completionPercentage: 94,
    campaignsCompleted: 34,
    onTimeDeliveryRate: 95,
    revisionRate: 8,
    avgResponseTime: '< 5h',
    socialLinks: social([
      { platform: 'youtube', handle: 'Vikram Gaming', followers: 385000, engagementRate: 4.3 },
      { platform: 'tiktok', handle: '@vikramgaming', followers: 127000, engagementRate: 3.8 },
      { platform: 'instagram', handle: '@vikram.gaming', followers: 145000, engagementRate: 4.0 },
    ]),
  }),
  creator({
    id: 'cr_mock_priya',
    userId: 'cr_mock_priya',
    displayName: 'Priya Makeup',
    username: 'priya.makeup.artist',
    bio: 'Makeup artist and beauty educator. Tutorials for south Indian brides, everyday makeup, and bridal makeup courses.',
    tagline: 'Glow up with Priya',
    location: 'Hyderabad, India',
    languages: ['English', 'Hindi', 'Telugu'],
    niches: ['Beauty', 'Makeup', 'Education'],
    availability: 'available',
    portfolioUrls: [],
    creatorScore: 88,
    creatorTier: 'verified_pro',
    completionPercentage: 96,
    campaignsCompleted: 45,
    onTimeDeliveryRate: 98,
    revisionRate: 6,
    avgResponseTime: '< 2h',
    socialLinks: social([
      { platform: 'instagram', handle: '@priya.makeup.artist', followers: 245000, engagementRate: 5.8 },
      { platform: 'youtube', handle: 'Priya Makeup', followers: 168000, engagementRate: 4.5 },
    ]),
  }),
  creator({
    id: 'cr_mock_arun',
    userId: 'cr_mock_arun',
    displayName: 'Arun Fitness',
    username: 'arun.fitness.pro',
    bio: 'Certified personal trainer and fitness influencer. Gym transformations, workout routines, and nutrition tips for beginners.',
    tagline: 'Transform your body, boost your confidence',
    location: 'Pune, India',
    languages: ['English', 'Marathi'],
    niches: ['Fitness', 'Health', 'Lifestyle'],
    availability: 'busy',
    portfolioUrls: [],
    creatorScore: 80,
    creatorTier: 'established',
    completionPercentage: 88,
    campaignsCompleted: 18,
    onTimeDeliveryRate: 92,
    revisionRate: 14,
    avgResponseTime: '< 8h',
    socialLinks: social([
      { platform: 'instagram', handle: '@arun.fitness.pro', followers: 320000, engagementRate: 5.1 },
      { platform: 'youtube', handle: 'Arun Fitness', followers: 198000, engagementRate: 4.2 },
    ]),
  }),
];

const iso = (d: string) => new Date(d).toISOString();

/** Sample campaigns for Discover Brands, Campaigns list, and Dashboard. */
export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'room-001',
    brandId: 'brand_mock_glowco',
    brandName: 'GlowCo India',
    title: 'Monsoon Glow',
    description:
      'GlowCo India\'s flagship monsoon campaign. We\'re seeking beauty and skincare creators to showcase our new hydration line for the monsoon season. Authentic content, real results.',
    type: 'sponsored_post',
    platforms: ['instagram', 'youtube'],
    contentFormats: ['reel', 'story', 'photo'],
    startDate: iso('2026-05-01'),
    endDate: iso('2026-07-15'),
    budget: 350000,
    currency: 'INR',
    slotsTotal: 5,
    slotsFilled: 1,
    status: 'active',
    visibility: 'public',
    deliverables: ['2 Instagram Reels', '3 Stories', '1 YouTube Short'],
    niche: 'Beauty/Skincare',
    applicationsCount: 12,
    createdAt: iso('2026-04-20'),
    brief: {
      toneOfVoice: 'Fresh, glowing, authentic',
      dos: ['Show before/after skincare routine', 'Feature GlowCo serum prominently'],
      donts: ['No competitor brand mentions', 'Avoid heavy filters'],
      mandatoryHashtags: ['#MonsoonGlow', '#GlowCoIndia'],
    },
  },
  {
    id: 'camp_mock_boat_audio',
    brandId: 'brand_mock_boat',
    brandName: 'boAt',
    title: 'Rockerz ANC — Monsoon campaign',
    description:
      'Seeking creators for punchy Reels and Shorts showcasing ANC in commute & gym scenarios. Ship product + hero assets; mandatory #DoWhatFloatsYourboAt.',
    type: 'product_review',
    platforms: ['instagram', 'youtube', 'tiktok'],
    contentFormats: ['reel', 'video', 'story'],
    startDate: iso('2026-05-01'),
    endDate: iso('2026-06-15'),
    budget: 520000,
    currency: 'INR',
    slotsTotal: 8,
    slotsFilled: 3,
    status: 'active',
    visibility: 'public',
    deliverables: ['2 Reels', '1 Short', '3 Stories'],
    niche: 'Tech',
    applicationsCount: 47,
    createdAt: iso('2026-04-28'),
    brief: {
      toneOfVoice: 'Bold, youthful, bass-forward',
      dos: ['Show real commute noise situations', 'Feature charging claim clearly'],
      donts: ['No competitor logos'],
      mandatoryHashtags: ['#boAt', '#ANC'],
    },
  },
  {
    id: 'camp_mock_mamaearth',
    brandId: 'brand_mock_mamaearth',
    brandName: 'Mamaearth',
    title: 'Vitamin C serum — summer glow UGC',
    description:
      'Micro & mid-tier skincare creators for before/after routines, GRWM hooks, and dermat-safe disclaimers. Prioritize lit-from-within aesthetic.',
    type: 'sponsored_post',
    platforms: ['instagram', 'youtube'],
    contentFormats: ['reel', 'story', 'photo'],
    startDate: iso('2026-05-10'),
    endDate: iso('2026-07-01'),
    budget: 850000,
    currency: 'INR',
    slotsTotal: 12,
    slotsFilled: 7,
    status: 'in_progress',
    visibility: 'public',
    deliverables: ['1 Reel', '5 Stories', '1 carousel'],
    niche: 'Beauty',
    applicationsCount: 112,
    createdAt: iso('2026-05-02'),
  },
  {
    id: 'camp_mock_zomato',
    brandId: 'brand_mock_zomato',
    brandName: 'Zomato',
    title: 'Inter-city food trail — creator edition',
    description:
      'Document hidden gems across 3 cities; emphasize Gold membership perks and delivery reliability. Collab with regional language hooks encouraged.',
    type: 'event_coverage',
    platforms: ['instagram', 'tiktok'],
    contentFormats: ['reel', 'video'],
    startDate: iso('2026-05-15'),
    endDate: iso('2026-06-30'),
    budget: 1200000,
    currency: 'INR',
    slotsTotal: 6,
    slotsFilled: 2,
    status: 'active',
    visibility: 'public',
    deliverables: ['3 Reels', '9 Stories'],
    niche: 'Food',
    applicationsCount: 63,
    createdAt: iso('2026-05-08'),
  },
  {
    id: 'camp_mock_nykaa',
    brandId: 'brand_mock_nykaa',
    brandName: 'Nykaa',
    title: 'Festive glam — affiliate push',
    description:
      'Affiliate-heavy campaign with trackable codes. Focus on dupes, tutorials, and cart-building Stories with swipe-ups.',
    type: 'affiliate',
    platforms: ['instagram', 'youtube'],
    contentFormats: ['reel', 'story', 'blog'],
    startDate: iso('2026-08-01'),
    endDate: iso('2026-09-30'),
    budget: 420000,
    currency: 'INR',
    slotsTotal: 20,
    slotsFilled: 0,
    status: 'draft',
    visibility: 'public',
    deliverables: ['Code in caption', '2 Reels'],
    niche: 'Fashion',
    applicationsCount: 0,
    createdAt: iso('2026-05-01'),
  },
  {
    id: 'camp_mock_done',
    brandId: 'brand_mock_swiggy',
    brandName: 'Swiggy',
    title: 'Instamart quick recipes — wrapped',
    description: 'Short-form recipe hacks using Instamart staples; campaign closed with strong ROI on saves.',
    type: 'sponsored_post',
    platforms: ['instagram'],
    contentFormats: ['reel'],
    startDate: iso('2026-02-01'),
    endDate: iso('2026-03-30'),
    budget: 380000,
    currency: 'INR',
    slotsTotal: 5,
    slotsFilled: 5,
    status: 'completed',
    visibility: 'public',
    deliverables: ['5 Reels'],
    niche: 'Food',
    applicationsCount: 28,
    createdAt: iso('2026-01-20'),
  },
  {
    id: 'camp_mock_myntra',
    brandId: 'brand_mock_myntra',
    brandName: 'Myntra',
    title: 'Summer fashion fest — UGC',
    description: 'Fashion creators for GRWM, outfit coordination, and haul videos showcasing summer collection.',
    type: 'sponsored_post',
    platforms: ['instagram', 'youtube', 'tiktok'],
    contentFormats: ['reel', 'video', 'story'],
    startDate: iso('2026-05-20'),
    endDate: iso('2026-07-30'),
    budget: 750000,
    currency: 'INR',
    slotsTotal: 15,
    slotsFilled: 9,
    status: 'active',
    visibility: 'public',
    deliverables: ['2 Reels', '10 Stories', '1 Video'],
    niche: 'Fashion',
    applicationsCount: 134,
    createdAt: iso('2026-05-05'),
  },
  {
    id: 'camp_mock_amazon',
    brandId: 'brand_mock_amazon',
    brandName: 'Amazon',
    title: 'Great Summer Sale — promo series',
    description: 'Deal highlights, product unboxings, and deal comparison videos for Amazon Summer Sale.',
    type: 'product_review',
    platforms: ['youtube', 'tiktok'],
    contentFormats: ['video', 'reel'],
    startDate: iso('2026-06-01'),
    endDate: iso('2026-06-30'),
    budget: 1500000,
    currency: 'INR',
    slotsTotal: 10,
    slotsFilled: 4,
    status: 'active',
    visibility: 'public',
    deliverables: ['5 Videos', '10 Reels'],
    niche: 'Tech',
    applicationsCount: 89,
    createdAt: iso('2026-05-12'),
  },
  {
    id: 'camp_mock_tanishq',
    brandId: 'brand_mock_tanishq',
    brandName: 'Tanishq',
    title: 'Bridal collection — wedding season',
    description: 'Wedding creators and fashion influencers for bridal jewelry showcase and styling tips.',
    type: 'brand_ambassador',
    platforms: ['instagram', 'youtube'],
    contentFormats: ['photo', 'video', 'reel'],
    startDate: iso('2026-06-15'),
    endDate: iso('2026-08-31'),
    budget: 1800000,
    currency: 'INR',
    slotsTotal: 8,
    slotsFilled: 3,
    status: 'active',
    visibility: 'public',
    deliverables: ['5 Posts', '3 Videos', '2 Reels'],
    niche: 'Fashion',
    applicationsCount: 52,
    createdAt: iso('2026-05-18'),
  },
  {
    id: 'camp_mock_lenskart',
    brandId: 'br_mock_lenskart',
    brandName: 'Lenskart',
    title: 'Eyewear fashion — trending frames',
    description: 'Style and fashion creators showcasing trendy eyewear frames and styling tips.',
    type: 'product_review',
    platforms: ['instagram', 'tiktok'],
    contentFormats: ['reel', 'story'],
    startDate: iso('2026-05-25'),
    endDate: iso('2026-07-15'),
    budget: 620000,
    currency: 'INR',
    slotsTotal: 10,
    slotsFilled: 6,
    status: 'active',
    visibility: 'public',
    deliverables: ['2 Reels', '8 Stories'],
    niche: 'Fashion',
    applicationsCount: 78,
    createdAt: iso('2026-05-10'),
  },
];

/** Sample contracts for Contracts page when backend has no rows (mock catalog). */
export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'demo-001',
    campaignId: 'camp_mock_mamaearth',
    brandId: 'brand_mock_mamaearth',
    creatorId: 'cr_mock_ananya',
    brandName: 'Mamaearth',
    creatorName: 'Ananya Rao',
    content: {
      parties: 'Mamaearth Beauty Pvt. Ltd. (Client) and Ananya Rao (Creator)',
      compensation: '₹1,65,000 to be held in ColabRoom Escrow and released within 48 hours of final content approval.',
      scope: 'The Creator shall produce one (1) high-quality Instagram Reel and three (3) Instagram Stories showcasing the Client’s Vitamin C serum line. Content must adhere to ASCI guidelines and clearly disclose the partnership.',
      liability: 'Both parties agree to standard mutual indemnification. Creator grants a 3-month digital usage right to the Client for paid amplification.',
      kill_fee: 'If the Client terminates this agreement within 72 hours of execution without cause, a 25% kill fee applies.'
    },
    status: 'sent',
    totalAmount: 165000,
    currency: 'INR',
    createdAt: iso('2026-05-03'),
    signedByBrandAt: iso('2026-05-04'),
  },
  {
    id: 'contract_mock_boat',
    campaignId: 'camp_mock_boat_audio',
    brandId: 'brand_mock_boat',
    creatorId: 'cr_mock_arjun',
    brandName: 'boAt',
    creatorName: 'Arjun Mehta',
    content: { 
      parties: 'Imagine Marketing Ltd. [boAt] (Client) and Arjun Mehta (Creator)',
      compensation: '₹3,45,000 total via ColabRoom Escrow. 50% upfront, 50% on completion.',
      scope: 'Production of one (1) dedicated YouTube review video (min 8 mins) and two (2) promotional YouTube Shorts. The Creator agrees to feature the Rockerz ANC series prominently.', 
      liability: 'The Creator maintains creative control but must avoid featuring competitor audio brands (e.g., JBL, Sony) in the same video.',
      kill_fee: 'No kill fee. Cancellation after script approval requires 100% payout.'
    },
    status: 'under_review',
    totalAmount: 345000,
    currency: 'INR',
    createdAt: iso('2026-05-06'),
  },
  {
    id: 'contract_mock_zomato',
    campaignId: 'camp_mock_zomato',
    brandId: 'brand_mock_zomato',
    creatorId: 'cr_mock_sara',
    brandName: 'Zomato',
    creatorName: 'Sara Khan',
    content: { 
      parties: 'Zomato Ltd. (Client) and Sara Khan (Creator)',
      compensation: '₹2,85,000 secured via ColabRoom Escrow.',
      scope: 'A three-part Instagram Reel series highlighting local hidden gems across three tier-2 cities. Content must integrate Zomato Gold perks seamlessly.', 
      liability: 'Creator agrees to adhere to the brand safety guidelines (no political, religious, or controversial statements in the content).',
      kill_fee: 'A 25% kill fee is applicable if the campaign is paused post-travel bookings.' 
    },
    status: 'signed',
    totalAmount: 285000,
    currency: 'INR',
    createdAt: iso('2026-05-09'),
    signedByBrandAt: iso('2026-05-10'),
    signedByCreatorAt: iso('2026-05-11'),
  },
  {
    id: 'contract_mock_amazon',
    campaignId: 'camp_mock_amazon',
    brandId: 'brand_mock_amazon',
    creatorId: 'cr_mock_deepa',
    brandName: 'Amazon',
    creatorName: 'Deepa Weds',
    content: { 
      parties: 'Amazon Seller Services Pvt. Ltd. (Client) and Deepa Weds (Creator)',
      compensation: '₹4,75,000 secured in Escrow.',
      scope: 'Creation of one (1) comprehensive Deal Highlight YouTube video and eight (8) Instagram Reels driving traffic via provided affiliate links.',
      liability: 'Strict compliance with ASCI advertising guidelines. All content must include "Paid Partnership" labels.',
      kill_fee: 'None. Subject to standard vendor terms.'
    },
    status: 'sent',
    totalAmount: 475000,
    currency: 'INR',
    createdAt: iso('2026-05-14'),
    signedByBrandAt: iso('2026-05-15'),
  },
  {
    id: 'contract_mock_lenskart',
    campaignId: 'camp_mock_lenskart',
    brandId: 'br_mock_lenskart',
    creatorId: 'cr_mock_priya',
    brandName: 'Lenskart',
    creatorName: 'Priya Makeup',
    content: { 
      parties: 'Lenskart Solutions Pvt. Ltd. (Client) and Priya Makeup (Creator)',
      compensation: '₹95,000 held in ColabRoom Escrow.',
      scope: 'One (1) Eyewear Styling Reel focusing on makeup pairing with glasses, plus five (5) accompanying Stories.',
      liability: 'Creator grants worldwide, royalty-free, perpetual license for the content to be re-posted on Lenskart social channels.',
      kill_fee: '15% if cancelled within 2 days of signing.'
    },
    status: 'executed',
    totalAmount: 95000,
    currency: 'INR',
    createdAt: iso('2026-05-12'),
    signedByBrandAt: iso('2026-05-13'),
    signedByCreatorAt: iso('2026-05-14'),
  },
  {
    id: 'contract_monsoon_glow',
    campaignId: 'room-001',
    brandId: 'brand_mock_glowco',
    creatorId: 'cr_mock_priya_sharma',
    brandName: 'GlowCo India',
    creatorName: 'Priya Sharma',
    content: {
      parties: 'GlowCo India Pvt. Ltd. (Client) and Priya Sharma (Creator)',
      compensation: '₹1,85,000 held in ColabRoom Escrow. Released in two tranches: 40% on draft approval, 60% on final published content.',
      scope: 'Two (2) Instagram Reels showcasing GlowCo Hydration Serum, three (3) Instagram Stories with swipe-up links, and one (1) YouTube Short. Content must include #MonsoonGlow and #GlowCoIndia hashtags. DELIVERABLES: 2 Reels, 3 Stories, 1 YouTube Short.',
      liability: 'Creator agrees to ASCI guidelines and must disclose paid partnership. GlowCo retains 3-month amplification rights.',
      kill_fee: '25% kill fee applies if brand cancels after content brief is shared.',
    },
    status: 'signed',
    totalAmount: 185000,
    currency: 'INR',
    createdAt: iso('2026-05-05'),
    signedByBrandAt: iso('2026-05-06'),
    signedByCreatorAt: iso('2026-05-07'),
  },
];


export function findMockCampaign(id: string): Campaign | undefined {
  return MOCK_CAMPAIGNS.find((c) => c.id === id);
}

export function findMockContract(id: string): Contract | undefined {
  return MOCK_CONTRACTS.find((c) => c.id === id);
}

export type BrandRow = BrandProfile & { id: string };

/** Sample brands if/when `brandsAPI.search` is used in the UI. */
export const MOCK_BRANDS: BrandRow[] = [
  {
    id: 'br_mock_boat',
    userId: 'brand_mock_boat',
    companyName: 'boAt',
    handle: 'boat-official',
    industry: 'Consumer electronics',
    companySize: '501–1000',
    website: 'https://www.boat-lifestyle.com',
    description: 'India’s leading audio wearable brand — earbuds, speakers, smartwatches.',
    values: 'Bold sound · Youth-first · Community',
    preferredNiches: ['Tech', 'Music', 'Fitness'],
    preferredPlatforms: ['instagram', 'youtube', 'tiktok'],
    brandScore: 89,
    brandTier: 'top_brand',
    avgPaymentTime: 2.1,
    campaignsCompleted: 210,
    onTimePaymentRate: 97,
    completionPercentage: 94,
  },
  {
    id: 'br_mock_mamaearth',
    userId: 'brand_mock_mamaearth',
    companyName: 'Mamaearth',
    handle: 'mamaearth-in',
    industry: 'Beauty & personal care',
    companySize: '1000+',
    website: 'https://mamaearth.in',
    description: 'Toxin-free skincare and babycare with plastic-positive recycling.',
    values: 'Honest ingredients · Sustainability',
    preferredNiches: ['Beauty', 'Lifestyle', 'Parenting'],
    preferredPlatforms: ['instagram', 'youtube'],
    brandScore: 92,
    brandTier: 'preferred',
    avgPaymentTime: 1.8,
    campaignsCompleted: 340,
    onTimePaymentRate: 99,
    completionPercentage: 96,
  },
  {
    id: 'br_mock_zomato',
    userId: 'brand_mock_zomato',
    companyName: 'Zomato',
    handle: 'zomato',
    industry: 'Food delivery',
    companySize: '1000+',
    website: 'https://www.zomato.com',
    description: 'Restaurant discovery, dining out, and quick commerce.',
    values: 'Discovery · Reliability · Hyperlocal',
    preferredNiches: ['Food', 'Travel'],
    preferredPlatforms: ['instagram', 'tiktok'],
    brandScore: 94,
    brandTier: 'top_brand',
    avgPaymentTime: 1.5,
    campaignsCompleted: 520,
    onTimePaymentRate: 98,
    completionPercentage: 98,
  },
  {
    id: 'brand_mock_myntra',
    userId: 'brand_mock_myntra',
    companyName: 'Myntra',
    handle: 'myntra-official',
    industry: 'Fashion & e-commerce',
    companySize: '1000+',
    website: 'https://www.myntra.com',
    description: 'India\'s largest online fashion retailer with trendy styles for everyone.',
    values: 'Style · Quality · Trust',
    preferredNiches: ['Fashion', 'Beauty', 'Lifestyle'],
    preferredPlatforms: ['instagram', 'youtube', 'tiktok'],
    brandScore: 91,
    brandTier: 'top_brand',
    avgPaymentTime: 1.9,
    campaignsCompleted: 380,
    onTimePaymentRate: 96,
    completionPercentage: 95,
  },
  {
    id: 'brand_mock_amazon',
    userId: 'brand_mock_amazon',
    companyName: 'Amazon',
    handle: 'amazon-in',
    industry: 'E-commerce',
    companySize: '1000+',
    website: 'https://www.amazon.in',
    description: 'Everything from electronics to fashion, delivered at your doorstep.',
    values: 'Customer first · Innovation · Speed',
    preferredNiches: ['Tech', 'Fashion', 'Lifestyle'],
    preferredPlatforms: ['youtube', 'instagram', 'tiktok'],
    brandScore: 95,
    brandTier: 'top_brand',
    avgPaymentTime: 1.5,
    campaignsCompleted: 650,
    onTimePaymentRate: 99,
    completionPercentage: 97,
  },
  {
    id: 'brand_mock_swiggy',
    userId: 'brand_mock_swiggy',
    companyName: 'Swiggy',
    handle: 'swiggy-in',
    industry: 'Food delivery',
    companySize: '1000+',
    website: 'https://www.swiggy.com',
    description: 'Get food delivered in minutes from your favorite restaurants.',
    values: 'Speed · Selection · Reliability',
    preferredNiches: ['Food', 'Lifestyle'],
    preferredPlatforms: ['instagram', 'tiktok'],
    brandScore: 90,
    brandTier: 'top_brand',
    avgPaymentTime: 1.7,
    campaignsCompleted: 290,
    onTimePaymentRate: 97,
    completionPercentage: 96,
  },
  {
    id: 'brand_mock_nykaa',
    userId: 'brand_mock_nykaa',
    companyName: 'Nykaa',
    handle: 'nykaa-online',
    industry: 'Beauty & e-commerce',
    companySize: '501–1000',
    website: 'https://www.nykaa.com',
    description: 'Your one-stop beauty destination with 1 million+ products.',
    values: 'Beauty · Authenticity · Empowerment',
    preferredNiches: ['Beauty', 'Fashion', 'Lifestyle'],
    preferredPlatforms: ['instagram', 'youtube'],
    brandScore: 88,
    brandTier: 'preferred',
    avgPaymentTime: 2.2,
    campaignsCompleted: 215,
    onTimePaymentRate: 94,
    completionPercentage: 92,
  },
  {
    id: 'brand_mock_tanishq',
    userId: 'brand_mock_tanishq',
    companyName: 'Tanishq',
    handle: 'tanishq-official',
    industry: 'Jewelry & luxury',
    companySize: '501–1000',
    website: 'https://www.tanishq.com',
    description: 'Premium gold and diamond jewelry for every celebration.',
    values: 'Purity · Tradition · Excellence',
    preferredNiches: ['Fashion', 'Weddings', 'Luxury'],
    preferredPlatforms: ['instagram', 'youtube'],
    brandScore: 93,
    brandTier: 'preferred',
    avgPaymentTime: 2.5,
    campaignsCompleted: 120,
    onTimePaymentRate: 98,
    completionPercentage: 97,
  },
  {
    id: 'br_mock_lenskart',
    userId: 'br_mock_lenskart',
    companyName: 'Lenskart',
    handle: 'lenskart-official',
    industry: 'Eyewear & optical',
    companySize: '501–1000',
    website: 'https://www.lenskart.com',
    description: 'Eyewear for every style and budget with home try-on facility.',
    values: 'Style · Quality · Affordability',
    preferredNiches: ['Fashion', 'Beauty', 'Lifestyle'],
    preferredPlatforms: ['instagram', 'tiktok', 'youtube'],
    brandScore: 87,
    brandTier: 'trusted',
    avgPaymentTime: 2.3,
    campaignsCompleted: 145,
    onTimePaymentRate: 95,
    completionPercentage: 93,
  },
  {
    id: 'brand_mock_glowco',
    userId: 'brand_mock_glowco',
    companyName: 'GlowCo India',
    handle: 'glowco-india',
    industry: 'Beauty & Skincare',
    companySize: '51–200',
    website: 'https://glowco.in',
    description: 'India\'s rising D2C skincare brand focused on clean, effective formulations for every skin type.',
    values: 'Clean beauty · Efficacy · Transparency',
    preferredNiches: ['Beauty/Skincare', 'Lifestyle', 'Fashion'],
    preferredPlatforms: ['instagram', 'youtube'],
    brandScore: 84,
    brandTier: 'trusted',
    avgPaymentTime: 2.1,
    campaignsCompleted: 18,
    onTimePaymentRate: 96,
    completionPercentage: 91,
  },
];

export function findMockBrandByHandle(handle: string): BrandRow | undefined {
  return MOCK_BRANDS.find((b) => b.handle === handle);
}
